Positions Table SDK
overlay-market/overlay-sdk pull request #7
Opened 2024-09-16 15:13 UTC by AndresImach

2024-09-25 06:02 UTC, djaciel requested changes

2024-09-25 06:02 UTC, djaciel commented on packages/overlay-sdk/src/positionsTables/openPositionsTable/openPositionsTable.ts
> +  LINKS,
LINKS constant must be removed and use NETWORKS for multichain instead

2024-09-25 06:02 UTC, djaciel commented on packages/overlay-sdk/src/positionsTables/openPositionsTable/openPositionsTable.ts
> +    const walletClient = "0x42e372d3ab3ac53036997bae6d1ab77c2ecd64b3";
Why is this hardcoded?

2024-09-25 06:02 UTC, djaciel commented on packages/overlay-sdk/src/positionsTables/unwindPositinosTable/unwindPositionsTable.ts
> +import { FIRST, LINKS, PRICE_CURRENCY_FROM_QUOTE } from "../../constants";
LINKS constant must be removed and use NETWORKS for multichain instead

2024-10-11 08:36 UTC, Aliona-D approved these changes

2024-10-13 21:02 UTC, merged